language: go
go:
  - 1.17.x
go_import_path: github.com/airtame/kommentaar
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
env:
  - GO111MODULE=off
script:
  - cd $HOME/gopath/src/github.com/airtame/kommentaar
  - ./bin/test -race ./...
  - ./bin/coverage ./...
  - ./bin/lint ./...
